#Allure Environment Properties
#Mon Feb 23 17:56:12 IST 2026
Java.Version=17.0.18
OS=Windows 10
Test\ URL=http\://192.168.1.105\:3000/
Browser.Version=145.0.7632.77
Environment=Staging
Quality\ Engineer=Pankaj
Browser=chrome
