#Allure Environment Properties
#Wed Feb 25 09:05:47 IST 2026
Java.Version=17.0.18
OS=Windows 10
Test\ URL=http\://3.84.224.180/
Browser.Version=145.0.7632.116
Environment=Staging
Quality\ Engineer=Pankaj
Browser=chrome
