#Allure Environment Properties
#Fri Feb 27 12:16:21 IST 2026
Java.Version=17.0.18
OS=Windows 10
Test\ URL=http\://3.84.224.180/
Browser.Version=145.0.7632.117
Environment=Staging
Quality\ Engineer=Pankaj
Browser=chrome
