name: Trigger Automation Tests

on:
  push:
    branches:
      - main   # When code is pushed to frontend main branch

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl -X POST \
          -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
          -F ref=main \
          https://gitlab.com/api/v4/projects/79628243/trigger/pipeline
